version: '2'
services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'dizzzan/simple-terraform']
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"